### PR TITLE
Revert "option to use xrootd or gfal with different protocols"

### PR DESCRIPTION
**Pull request by mangano**
Reverts MT2Analysis/MT2Analysis2015#379

### CODE REVIEW

**Comment by mangano** [comment]
Traceback (most recent call last):
  File "skimBabies.py", line 65, in <module>
    print "-> chosen to use gfal via "+gfalProtocol+" protocol"
NameError: name 'gfalProtocol' is not defined

**Comment by mangano** [comment]
@brucala Have you tested this on the batch or only interactively ?

**Comment by brucala** [comment]
I had actually tested it only on the batch, not interactively. 
I see a couple of bug fixes in the next PRs, sorry about that. Is all looking good now?

**Comment by mangano** [comment]
Yes, it should be fixed now for the default configuration

**Pull request merged**
